@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create-account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Leonardo Maciel Deschamps",
  "email": "leonardomacieldeschamps@gmail.com",
  "password": "781227"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "leonardomacieldeschamps@gmail.com",
  "password": "781227"
}

###

# @name create-question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta",
  "content": "Conteúdo da pergunta"
}

###

# @name fetch-recent-questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}